### ISSUE TITLE
Обновление зависимостей

### ISSUE THREAD

**Issue by aimuzov** [alexbaumgertner/sails-bem-project-stub#10]
Как думаете, нужно ли это? Я попробовал, знаний enb маловато, сборка ломается, причин понять не могу. Возможно из-за того что deps не совпадает с новыми требованиями технологии:
https://github.com/enb-bem/enb-bem-techs/blob/v2.0.0/MIGRATION-2.md#Технология-deps-old

**Comment by alexbaumgertner** [comment]
@Immuzov покажите пожалуйста лог сборки.

**Comment by aimuzov** [comment]
@alexbaumgertner, получилось апнуть версии. Посмотрите [PR](https://github.com/alexbaumgertner/sails-bem-project-stub/pull/11).

**Comment by alexbaumgertner** [comment]
Done! Спасибо огромное!

**Comment by alexbaumgertner** [comment]
Сделано в https://github.com/bem-under-sailsjs/sails-bem-project-stub/pull/11
