### ISSUE TITLE
Add BH template engine support.

### ISSUE THREAD

**Issue by georg-malahov** [alexbaumgertner/sails-bem-project-stub#8]
Because of its [advantages](https://en.bem.info/technology/bh/v4.1.1/about/#advantages), I think it is a good idea to start supporting it.

**Ideas:**
- Choose what kind of template engine to use from configs;
- Auto-detect existing BH and BEMHTML template files and use available;
- Extend [sails-hook-bem-render](https://www.npmjs.com/package/sails-hook-bem-render) with these features or write a new one.

**Comment by alexbaumgertner** [comment]
@yuriMalakhov will be nice if you send pull request with BH-templates :)

**Comment by alexbaumgertner** [comment]
Then I'll add BH support https://github.com/alexbaumgertner/sails-hook-bem-render/issues/7
